[project]
name = "jiram-catalog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bokeh>=3.9.2",
    "certifi>=2026.7.22",
    "datashader>=0.19.1",
    "fastapi>=0.141.1",
    "holoviews>=1.23.2",
    "hvplot>=0.12.2",
    "imageio>=2.37.4",
    "imageio-ffmpeg>=0.6.0",
    "matplotlib>=3.11.1",
    "netcdf4>=1.7.4",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "panel>=1.9.4",
    "param>=2.4.2",
    "pvl>=1.3.2",
    "pyarrow>=25.0.1",
    "pyyaml>=6.0.3",
    "spiceypy>=8.2.0",
    "uvicorn[standard]>=0.52.4",
    "xarray>=2026.7.0",
]

[project.scripts]
jiram-catalog = "jiram_catalog.cli:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]
